# -*- coding: utf-8 -*-
"""AI-Engineering(Evalution,Export and Optimization).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wi5sOy74vnHEDhb_yK93M9EdOzWmm-Rp
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/bgmgncr/AI-Engineering-Evalution-Export-and-Optimization.git
# %cd AI-Engineering-Evalution-Export-and-Optimization

# Commented out IPython magic to ensure Python compatibility.
# %cd AI-Engineering-Evalution-Export-and-Optimization
!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!ls -la

!ls -la benchmark.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile benchmark.py
# import argparse
# import json
# import time
# from pathlib import Path
# 
# import numpy as np
# import pandas as pd
# 
# from ultralytics import YOLO
# import onnxruntime as ort
# 
# 
# DEFAULT_IMAGES = [
#     "data_samples/bus.jpg",
#     "data_samples/zidane.jpg",
# ]
# 
# 
# def parse_args():
#     p = argparse.ArgumentParser()
#     p.add_argument("--backend", choices=["pytorch", "onnx"], required=True)
#     p.add_argument("--images", type=int, default=10)
#     p.add_argument("--out", type=str, default="results/")
#     p.add_argument("--weights", type=str, default="yolov8n.pt")  # for pytorch
#     p.add_argument("--onnx_path", type=str, default="yolov8n.onnx")
#     p.add_argument("--imgsz", type=int, default=640)
#     p.add_argument("--warmup", type=int, default=10)
#     return p.parse_args()
# 
# 
# def summarize_latency_ms(samples_ms):
#     s = np.asarray(samples_ms, dtype=float)
#     return {
#         "mean_ms": float(s.mean()),
#         "p50_ms": float(np.percentile(s, 50)),
#         "p95_ms": float(np.percentile(s, 95)),
#     }
# 
# 
# def get_image_list(n):
#     return (DEFAULT_IMAGES * ((n + len(DEFAULT_IMAGES) - 1) // len(DEFAULT_IMAGES)))[:n]
# 
# 
# def run_ultralytics_backend(model, image_list, imgsz, warmup, device):
#     # Warmup
#     for _ in range(warmup):
#         _ = model.predict(image_list[0], imgsz=imgsz, verbose=False, device=device)
# 
#     predictions = []
#     times_ms = []
# 
#     for i, img in enumerate(image_list):
#         t0 = time.perf_counter()
#         res = model.predict(img, imgsz=imgsz, verbose=False, device=device)[0]
#         # sync for accurate GPU timing (safe even if CPU)
#         try:
#             import torch
#             if torch.cuda.is_available():
#                 torch.cuda.synchronize()
#         except Exception:
#             pass
#         t1 = time.perf_counter()
#         times_ms.append((t1 - t0) * 1000.0)
# 
#         if res.boxes is not None and len(res.boxes) > 0:
#             xyxy = res.boxes.xyxy.cpu().numpy()
#             conf = res.boxes.conf.cpu().numpy()
#             cls = res.boxes.cls.cpu().numpy().astype(int)
# 
#             for j in range(len(cls)):
#                 predictions.append(
#                     {
#                         "image_id": f"img_{i:04d}",
#                         "class_id": int(cls[j]),
#                         "score": float(conf[j]),
#                         "bbox_xyxy": [float(x) for x in xyxy[j].tolist()],
#                     }
#                 )
# 
#     return predictions, times_ms
# 
# 
# def write_outputs(out_dir, backend, images, imgsz, predictions, times_ms):
#     (out_dir / f"predictions_{backend}.json").write_text(json.dumps(predictions, indent=2))
# 
#     lat = summarize_latency_ms(times_ms)
#     latency_df = pd.DataFrame([{
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         **lat
#     }])
#     latency_df.to_csv(out_dir / f"latency_{backend}.csv", index=False)
# 
#     # Placeholder metrics for now
#     metrics_df = pd.DataFrame([{
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         "mAP50": None
#     }])
#     metrics_df.to_csv(out_dir / f"metrics_{backend}.csv", index=False)
# 
#     print("Wrote:", out_dir / f"predictions_{backend}.json")
#     print("Wrote:", out_dir / f"latency_{backend}.csv")
#     print("Wrote:", out_dir / f"metrics_{backend}.csv")
# 
# 
# 
# def main():
#     args = parse_args()
#     backend = args.backend
#     out_dir = Path(args.out)
#     out_dir.mkdir(parents=True, exist_ok=True)
# 
#     image_list = get_image_list(args.images)
# 
#     if args.backend == "pytorch":
#         model = YOLO(args.weights)
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # Changed from 'cpu' to 0 for GPU
#         )
#         write_outputs(out_dir, "pytorch", args.images, args.imgsz, preds, times_ms)
# 
#     elif args.backend == "onnx":
#         # Ensure CUDA provider exists
#         providers = ort.get_available_providers()
#         if "CUDAExecutionProvider" not in providers:
#             raise RuntimeError(f"CUDAExecutionProvider not available. Providers: {providers}")
# 
#         model = YOLO(args.onnx_path)  # Ultralytics will run ONNX via onnxruntime
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # GPU
#         )
#         write_outputs(out_dir, "onnx", args.images, args.imgsz, preds, times_ms)
# 
# 
# if __name__ == "__main__":
#     main()

# Commented out IPython magic to ensure Python compatibility.
import os

repo_dir = "AI-Engineering-Evalution-Export-and-Optimization"
current_path = os.getcwd()

# Ensure we are in the correct directory (repo root)
if not current_path.endswith(repo_dir):
#     %cd {repo_dir}

# List the contents of the results directory
!ls results/

# Commented out IPython magic to ensure Python compatibility.
import os

repo_dir = "AI-Engineering-Evalution-Export-and-Optimization"
current_path = os.getcwd()

# Ensure we are in the correct directory (repo root)
if not current_path.endswith(repo_dir):
#     %cd {repo_dir}

# List the contents of the results directory to show the created CSV files
!ls results/

"""# Task
Benchmark YOLOv8n models using PyTorch and ONNX backends on GPU, saving the latency and metrics results to "/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/", and then summarize the generated results including latency metrics for GPU performance comparison.

## Mount Google Drive

### Subtask:
Mount the user's Google Drive to make it accessible within the Colab environment. This is a prerequisite for saving files directly to Drive.

**Reasoning**:
Mount Google Drive to make it accessible within the Colab environment for saving files to Drive.
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile benchmark.py
# import argparse
# import json
# import time
# from pathlib import Path
# 
# import numpy as np
# import pandas as pd
# 
# from ultralytics import YOLO
# import onnxruntime as ort
# import os # Added import os
# 
# 
# DEFAULT_IMAGES = [
#     "data_samples/bus.jpg",
#     "data_samples/zidane.jpg",
# ]
# 
# 
# def parse_args():
#     p = argparse.ArgumentParser()
#     p.add_argument("--backend", choices=["pytorch", "onnx"], required=True)
#     p.add_argument("--images", type=int, default=10)
#     p.add_argument("--out", type=str, default="results/")
#     p.add_argument("--weights", type=str, default="yolov8n.pt")  # for pytorch
#     p.add_argument("--onnx_path", type=str, default="yolov8n.onnx")
#     p.add_argument("--imgsz", type=int, default=640)
#     p.add_argument("--warmup", type=int, default=10)
#     return p.parse_args()
# 
# 
# def summarize_latency_ms(samples_ms):
#     s = np.asarray(samples_ms, dtype=float)
#     return {
#         "mean_ms": float(s.mean()),
#         "p50_ms": float(np.percentile(s, 50)),
#         "p95_ms": float(np.percentile(s, 95)),
#     }
# 
# 
# def get_image_list(n):
#     return (DEFAULT_IMAGES * ((n + len(DEFAULT_IMAGES) - 1) // len(DEFAULT_IMAGES)))[:n]
# 
# 
# def run_ultralytics_backend(model, image_list, imgsz, warmup, device):
#     # Warmup
#     for _ in range(warmup):
#         _ = model.predict(image_list[0], imgsz=imgsz, verbose=False, device=device)
# 
#     predictions = []
#     times_ms = []
# 
#     for i, img in enumerate(image_list):
#         t0 = time.perf_counter()
#         res = model.predict(img, imgsz=imgsz, verbose=False, device=device)[0]
#         # sync for accurate GPU timing (safe even if CPU)
#         try:
#             import torch
#             if torch.cuda.is_available():
#                 torch.cuda.synchronize()
#         except Exception:
#             pass
#         t1 = time.perf_counter()
#         times_ms.append((t1 - t0) * 1000.0)
# 
#         if res.boxes is not None and len(res.boxes) > 0:
#             xyxy = res.boxes.xyxy.cpu().numpy()
#             conf = res.boxes.conf.cpu().numpy()
#             cls = res.boxes.cls.cpu().numpy().astype(int)
# 
#             for j in range(len(cls)):
#                 predictions.append(
#                     {
#                         "image_id": f"img_{i:04d}",
#                         "class_id": int(cls[j]),
#                         "score": float(conf[j]),
#                         "bbox_xyxy": [float(x) for x in xyxy[j].tolist()],
#                     }
#                 )
# 
#     return predictions, times_ms
# 
# 
# def write_outputs(out_dir, backend, images, imgsz, predictions, times_ms):
#     (out_dir / f"predictions_{backend}.json").write_text(json.dumps(predictions, indent=2))
# 
#     lat = summarize_latency_ms(times_ms)
#     latency_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         **lat
#     }
#     ])
#     latency_df.to_csv(out_dir / f"latency_{backend}.csv", index=False)
# 
#     # Placeholder metrics for now
#     metrics_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         "mAP50": None
#     }
#     ])
#     metrics_df.to_csv(out_dir / f"metrics_{backend}.csv", index=False)
# 
#     print("Wrote:", out_dir / f"predictions_{backend}.json")
#     print("Wrote:", out_dir / f"latency_{backend}.csv")
#     print("Wrote:", out_dir / f"metrics_{backend}.csv")
# 
# 
# 
# def main():
#     args = parse_args()
#     backend = args.backend
#     out_dir = Path(args.out)
#     out_dir.mkdir(parents=True, exist_ok=True)
# 
#     image_list = get_image_list(args.images)
# 
#     if args.backend == "pytorch":
#         model = YOLO(args.weights)
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # Changed from 'cpu' to 0 for GPU
#         )
#         write_outputs(out_dir, "pytorch", args.images, args.imgsz, preds, times_ms)
# 
#     elif args.backend == "onnx":
#         # Explicitly create InferenceSession with CUDA provider and pass to YOLO's internal backend
#         # Ultralytics YOLO constructor handles ONNX via its internal ONNXRuntimeBackend.
#         # The ONNXRuntimeBackend constructor takes `providers` argument.
#         # However, passing providers directly to YOLO() constructor for ONNX path is not supported.
#         # Instead, we will instantiate ONNXRuntimeBackend directly and pass it to YOLO.
# 
#         # First, check available providers for debugging
#         print(f"ONNX Runtime available providers (inside benchmark.py): {ort.get_available_providers()}")
# 
#         # Create InferenceSession with CUDA provider
#         sess_options = ort.SessionOptions()
#         onnx_session = ort.InferenceSession(args.onnx_path, sess_options=sess_options, providers=['CUDAExecutionProvider'])
# 
#         # Instantiate YOLO's ONNXRuntimeBackend and pass the custom session
#         # This requires importing ONNXRuntimeBackend directly if YOLO() doesn't expose it.
#         # Alternatively, if YOLO(args.onnx_path) directly passes providers, we can use that.
#         # Given previous TypeErrors, let's try setting environment variable
# 
#         # Setting environment variable to force CUDA for ONNX Runtime
#         os.environ["ORT_CUDA_EP_ENABLED"] = "1"
#         os.environ["ORT_TENSORRT_EP_ENABLED"] = "1" # Also enable TRT EP if available for further optimization
# 
#         # Then let YOLO load the ONNX model, it should pick up the environment variable
#         model = YOLO(args.onnx_path)
# 
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # GPU
#         )
#         write_outputs(out_dir, "onnx", args.images, args.imgsz, preds, times_ms)
# 
# 
# if __name__ == "__main__":
#     main()

import os
import requests

# Create data_samples directory if it doesn't exist
data_samples_dir = "data_samples"
os.makedirs(data_samples_dir, exist_ok=True)

# Define image URLs and local paths
image_urls = {
    "bus.jpg": "https://ultralytics.com/images/bus.jpg",
    "zidane.jpg": "https://ultralytics.com/images/zidane.jpg"
}

# Download images
for filename, url in image_urls.items():
    filepath = os.path.join(data_samples_dir, filename)
    if not os.path.exists(filepath):
        print(f"Downloading {filename}...")
        r = requests.get(url, stream=True)
        r.raise_for_status() # Raise an exception for HTTP errors
        with open(filepath, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"Downloaded {filename}")
    else:
        print(f"{filename} already exists, skipping download.")

print(f"Contents of {data_samples_dir}:")
!ls {data_samples_dir}

"""**Reasoning**:
Now that the `benchmark.py` script is available, dependencies are installed, and sample images are downloaded, the next step is to run the benchmarking for the PyTorch backend on GPU. The results will be saved to the specified Google Drive path, which needs to be created first.


"""

import os

# Define the output directory in Google Drive
output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Create the output directory if it doesn't exist
os.makedirs(output_dir_drive, exist_ok=True)
print(f"Ensured output directory exists: {output_dir_drive}")

# Run the benchmark for PyTorch backend on GPU
# The script is designed to use device=0 (GPU) when onnxruntime-gpu is installed
get_ipython().system(f'python benchmark.py --backend pytorch --out "{output_dir_drive}" --imgsz 640 --images 10')

"""**Reasoning**:
The `benchmark.py` script has been corrected. Now, I need to re-run the benchmarking for the PyTorch backend on GPU using the corrected script. This will generate the performance results and save them to the specified Google Drive path.


"""

import os

# Define the output directory in Google Drive
output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Create the output directory if it doesn't exist (already done in previous step, but harmless to repeat)
os.makedirs(output_dir_drive, exist_ok=True)
print(f"Ensured output directory exists: {output_dir_drive}")

# Run the benchmark for PyTorch backend on GPU
# The script is designed to use device=0 (GPU) when onnxruntime-gpu is installed
get_ipython().system(f'python benchmark.py --backend pytorch --out "{output_dir_drive}" --imgsz 640 --images 10')

"""**Reasoning**:
The PyTorch backend benchmarking has been completed. The next step is to perform the benchmarking for the ONNX backend using the same corrected `benchmark.py` script. The results will be saved to the same Google Drive path, alongside the PyTorch results.


"""

import os

# Define the output directory in Google Drive
output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Create the output directory if it doesn't exist (already done in previous step, but harmless to repeat)
os.makedirs(output_dir_drive, exist_ok=True)
print(f"Ensured output directory exists: {output_dir_drive}")

# Run the benchmark for ONNX backend on GPU
# The script is designed to use device=0 (GPU) when onnxruntime-gpu is installed
# Note: This will download yolov8n.onnx if not already present.
get_ipython().system(f'python benchmark.py --backend onnx --out "{output_dir_drive}" --imgsz 640 --images 10')

"""**Reasoning**:
The previous step failed because the `yolov8n.onnx` model was not found. I need to export the `yolov8n.pt` PyTorch model to ONNX format before it can be used for ONNX benchmarking. This will create the required `yolov8n.onnx` file in the current directory.


"""

from ultralytics import YOLO

# Load the PyTorch YOLOv8n model
model = YOLO('yolov8n.pt')

# Export the model to ONNX format
# The output file will be yolov8n.onnx in the current directory
model.export(format='onnx', imgsz=640)

print("YOLOv8n model exported to yolov8n.onnx")

"""**Reasoning**:
The `yolov8n.onnx` model has now been successfully exported. The next logical step is to re-run the benchmarking for the ONNX backend, as the required ONNX model file is now available.


"""

import os

# Define the output directory in Google Drive
output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Create the output directory if it doesn't exist (already done in previous step, but harmless to repeat)
os.makedirs(output_dir_drive, exist_ok=True)
print(f"Ensured output directory exists: {output_dir_drive}")

# Run the benchmark for ONNX backend on GPU
# The script is designed to use device=0 (GPU) when onnxruntime-gpu is installed
# Note: This will download yolov8n.onnx if not already present.
get_ipython().system(f'python benchmark.py --backend onnx --out "{output_dir_drive}" --imgsz 640 --images 10')

"""**Reasoning**:
The `RuntimeError: CUDAExecutionProvider not available` indicates that ONNX Runtime is not correctly utilizing the GPU, despite `onnxruntime-gpu` being installed. This often happens if the CUDA provider isn't explicitly prioritized or found. To fix this, I will modify the `benchmark.py` script to explicitly set `providers=['CUDAExecutionProvider']` when initializing the ONNX Runtime session, ensuring it attempts to use the GPU.


"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile benchmark.py
# import argparse
# import json
# import time
# from pathlib import Path
# 
# import numpy as np
# import pandas as pd
# 
# from ultralytics import YOLO
# import onnxruntime as ort
# 
# 
# DEFAULT_IMAGES = [
#     "data_samples/bus.jpg",
#     "data_samples/zidane.jpg",
# ]
# 
# 
# def parse_args():
#     p = argparse.ArgumentParser()
#     p.add_argument("--backend", choices=["pytorch", "onnx"], required=True)
#     p.add_argument("--images", type=int, default=10)
#     p.add_argument("--out", type=str, default="results/")
#     p.add_argument("--weights", type=str, default="yolov8n.pt")  # for pytorch
#     p.add_argument("--onnx_path", type=str, default="yolov8n.onnx")
#     p.add_argument("--imgsz", type=int, default=640)
#     p.add_argument("--warmup", type=int, default=10)
#     return p.parse_args()
# 
# 
# def summarize_latency_ms(samples_ms):
#     s = np.asarray(samples_ms, dtype=float)
#     return {
#         "mean_ms": float(s.mean()),
#         "p50_ms": float(np.percentile(s, 50)),
#         "p95_ms": float(np.percentile(s, 95)),
#     }
# 
# 
# def get_image_list(n):
#     return (DEFAULT_IMAGES * ((n + len(DEFAULT_IMAGES) - 1) // len(DEFAULT_IMAGES)))[:n]
# 
# 
# def run_ultralytics_backend(model, image_list, imgsz, warmup, device):
#     # Warmup
#     for _ in range(warmup):
#         _ = model.predict(image_list[0], imgsz=imgsz, verbose=False, device=device)
# 
#     predictions = []
#     times_ms = []
# 
#     for i, img in enumerate(image_list):
#         t0 = time.perf_counter()
#         res = model.predict(img, imgsz=imgsz, verbose=False, device=device)[0]
#         # sync for accurate GPU timing (safe even if CPU)
#         try:
#             import torch
#             if torch.cuda.is_available():
#                 torch.cuda.synchronize()
#         except Exception:
#             pass
#         t1 = time.perf_counter()
#         times_ms.append((t1 - t0) * 1000.0)
# 
#         if res.boxes is not None and len(res.boxes) > 0:
#             xyxy = res.boxes.xyxy.cpu().numpy()
#             conf = res.boxes.conf.cpu().numpy()
#             cls = res.boxes.cls.cpu().numpy().astype(int)
# 
#             for j in range(len(cls)):
#                 predictions.append(
#                     {
#                         "image_id": f"img_{i:04d}",
#                         "class_id": int(cls[j]),
#                         "score": float(conf[j]),
#                         "bbox_xyxy": [float(x) for x in xyxy[j].tolist()],
#                     }
#                 )
# 
#     return predictions, times_ms
# 
# 
# def write_outputs(out_dir, backend, images, imgsz, predictions, times_ms):
#     (out_dir / f"predictions_{backend}.json").write_text(json.dumps(predictions, indent=2))
# 
#     lat = summarize_latency_ms(times_ms)
#     latency_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         **lat
#     }
#     ])
#     latency_df.to_csv(out_dir / f"latency_{backend}.csv", index=False)
# 
#     # Placeholder metrics for now
#     metrics_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         "mAP50": None
#     }
#     ])
#     metrics_df.to_csv(out_dir / f"metrics_{backend}.csv", index=False)
# 
#     print("Wrote:", out_dir / f"predictions_{backend}.json")
#     print("Wrote:", out_dir / f"latency_{backend}.csv")
#     print("Wrote:", out_dir / f"metrics_{backend}.csv")
# 
# 
# 
# def main():
#     args = parse_args()
#     backend = args.backend
#     out_dir = Path(args.out)
#     out_dir.mkdir(parents=True, exist_ok=True)
# 
#     image_list = get_image_list(args.images)
# 
#     if args.backend == "pytorch":
#         model = YOLO(args.weights)
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # Changed from 'cpu' to 0 for GPU
#         )
#         write_outputs(out_dir, "pytorch", args.images, args.imgsz, preds, times_ms)
# 
#     elif args.backend == "onnx":
#         # Explicitly set providers to include CUDAExecutionProvider
#         providers = ['CUDAExecutionProvider']
#         sess_options = ort.SessionOptions()
#         model = YOLO(args.onnx_path, session=ort.InferenceSession(args.onnx_path, sess_options, providers=providers))  # Ultralytics will run ONNX via onnxruntime
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # GPU
#         )
#         write_outputs(out_dir, "onnx", args.images, args.imgsz, preds, times_ms)
# 
# 
# if __name__ == "__main__":
#     main()
#

"""**Reasoning**:
The `benchmark.py` script has been corrected to explicitly use the `CUDAExecutionProvider` for ONNX Runtime. Now, I need to re-run the benchmarking for the ONNX backend to ensure it utilizes the GPU and correctly generates the performance results, saving them to the specified Google Drive path.


"""

import os

# Define the output directory in Google Drive
output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Create the output directory if it doesn't exist (already done in previous step, but harmless to repeat)
os.makedirs(output_dir_drive, exist_ok=True)
print(f"Ensured output directory exists: {output_dir_drive}")

# Run the benchmark for ONNX backend on GPU
# The script is designed to use device=0 (GPU) when onnxruntime-gpu is installed
get_ipython().system(f'python benchmark.py --backend onnx --out "{output_dir_drive}" --imgsz 640 --images 10')

"""**Reasoning**:
The previous error `TypeError: YOLO.__init__() got an unexpected keyword argument 'session'` indicates that the `ultralytics.YOLO` constructor does not directly accept an `onnxruntime.InferenceSession` object. Instead, when loading an ONNX model, `YOLO` expects the path to the ONNX model and internally manages the ONNX Runtime session. I need to revert the change that explicitly passed a session object and allow `ultralytics` to handle the ONNX model loading by simply providing the ONNX path and device.


"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile benchmark.py
# import argparse
# import json
# import time
# from pathlib import Path
# 
# import numpy as np
# import pandas as pd
# 
# from ultralytics import YOLO
# import onnxruntime as ort
# 
# 
# DEFAULT_IMAGES = [
#     "data_samples/bus.jpg",
#     "data_samples/zidane.jpg",
# ]
# 
# 
# def parse_args():
#     p = argparse.ArgumentParser()
#     p.add_argument("--backend", choices=["pytorch", "onnx"], required=True)
#     p.add_argument("--images", type=int, default=10)
#     p.add_argument("--out", type=str, default="results/")
#     p.add_argument("--weights", type=str, default="yolov8n.pt")  # for pytorch
#     p.add_argument("--onnx_path", type=str, default="yolov8n.onnx")
#     p.add_argument("--imgsz", type=int, default=640)
#     p.add_argument("--warmup", type=int, default=10)
#     return p.parse_args()
# 
# 
# def summarize_latency_ms(samples_ms):
#     s = np.asarray(samples_ms, dtype=float)
#     return {
#         "mean_ms": float(s.mean()),
#         "p50_ms": float(np.percentile(s, 50)),
#         "p95_ms": float(np.percentile(s, 95)),
#     }
# 
# 
# def get_image_list(n):
#     return (DEFAULT_IMAGES * ((n + len(DEFAULT_IMAGES) - 1) // len(DEFAULT_IMAGES)))[:n]
# 
# 
# def run_ultralytics_backend(model, image_list, imgsz, warmup, device):
#     # Warmup
#     for _ in range(warmup):
#         _ = model.predict(image_list[0], imgsz=imgsz, verbose=False, device=device)
# 
#     predictions = []
#     times_ms = []
# 
#     for i, img in enumerate(image_list):
#         t0 = time.perf_counter()
#         res = model.predict(img, imgsz=imgsz, verbose=False, device=device)[0]
#         # sync for accurate GPU timing (safe even if CPU)
#         try:
#             import torch
#             if torch.cuda.is_available():
#                 torch.cuda.synchronize()
#         except Exception:
#             pass
#         t1 = time.perf_counter()
#         times_ms.append((t1 - t0) * 1000.0)
# 
#         if res.boxes is not None and len(res.boxes) > 0:
#             xyxy = res.boxes.xyxy.cpu().numpy()
#             conf = res.boxes.conf.cpu().numpy()
#             cls = res.boxes.cls.cpu().numpy().astype(int)
# 
#             for j in range(len(cls)):
#                 predictions.append(
#                     {
#                         "image_id": f"img_{i:04d}",
#                         "class_id": int(cls[j]),
#                         "score": float(conf[j]),
#                         "bbox_xyxy": [float(x) for x in xyxy[j].tolist()],
#                     }
#                 )
# 
#     return predictions, times_ms
# 
# 
# def write_outputs(out_dir, backend, images, imgsz, predictions, times_ms):
#     (out_dir / f"predictions_{backend}.json").write_text(json.dumps(predictions, indent=2))
# 
#     lat = summarize_latency_ms(times_ms)
#     latency_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         **lat
#     }
#     ])
#     latency_df.to_csv(out_dir / f"latency_{backend}.csv", index=False)
# 
#     # Placeholder metrics for now
#     metrics_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         "mAP50": None
#     }
#     ])
#     metrics_df.to_csv(out_dir / f"metrics_{backend}.csv", index=False)
# 
#     print("Wrote:", out_dir / f"predictions_{backend}.json")
#     print("Wrote:", out_dir / f"latency_{backend}.csv")
#     print("Wrote:", out_dir / f"metrics_{backend}.csv")
# 
# 
# 
# def main():
#     args = parse_args()
#     backend = args.backend
#     out_dir = Path(args.out)
#     out_dir.mkdir(parents=True, exist_ok=True)
# 
#     image_list = get_image_list(args.images)
# 
#     if args.backend == "pytorch":
#         model = YOLO(args.weights)
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # Changed from 'cpu' to 0 for GPU
#         )
#         write_outputs(out_dir, "pytorch", args.images, args.imgsz, preds, times_ms)
# 
#     elif args.backend == "onnx":
#         # Revert changes: Ultralytics YOLO constructor handles ONNX session internally
#         # and implicitly uses CUDA if onnxruntime-gpu is installed and CUDA is available.
#         # Removing explicit session passing that caused TypeError.
#         model = YOLO(args.onnx_path)  # Ultralytics will run ONNX via onnxruntime
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # GPU
#         )
#         write_outputs(out_dir, "onnx", args.images, args.imgsz, preds, times_ms)
# 
# 
# if __name__ == "__main__":
#     main()
#

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile benchmark.py
# import argparse
# import json
# import time
# from pathlib import Path
# 
# import numpy as np
# import pandas as pd
# 
# from ultralytics import YOLO
# import onnxruntime as ort
# 
# 
# DEFAULT_IMAGES = [
#     "data_samples/bus.jpg",
#     "data_samples/zidane.jpg",
# ]
# 
# 
# def parse_args():
#     p = argparse.ArgumentParser()
#     p.add_argument("--backend", choices=["pytorch", "onnx"], required=True)
#     p.add_argument("--images", type=int, default=10)
#     p.add_argument("--out", type=str, default="results/")
#     p.add_argument("--weights", type=str, default="yolov8n.pt")  # for pytorch
#     p.add_argument("--onnx_path", type=str, default="yolov8n.onnx")
#     p.add_argument("--imgsz", type=int, default=640)
#     p.add_argument("--warmup", type=int, default=10)
#     return p.parse_args()
# 
# 
# def summarize_latency_ms(samples_ms):
#     s = np.asarray(samples_ms, dtype=float)
#     return {
#         "mean_ms": float(s.mean()),
#         "p50_ms": float(np.percentile(s, 50)),
#         "p95_ms": float(np.percentile(s, 95)),
#     }
# 
# 
# def get_image_list(n):
#     return (DEFAULT_IMAGES * ((n + len(DEFAULT_IMAGES) - 1) // len(DEFAULT_IMAGES)))[:n]
# 
# 
# def run_ultralytics_backend(model, image_list, imgsz, warmup, device):
#     # Warmup
#     for _ in range(warmup):
#         _ = model.predict(image_list[0], imgsz=imgsz, verbose=False, device=device)
# 
#     predictions = []
#     times_ms = []
# 
#     for i, img in enumerate(image_list):
#         t0 = time.perf_counter()
#         res = model.predict(img, imgsz=imgsz, verbose=False, device=device)[0]
#         # sync for accurate GPU timing (safe even if CPU)
#         try:
#             import torch
#             if torch.cuda.is_available():
#                 torch.cuda.synchronize()
#         except Exception:
#             pass
#         t1 = time.perf_counter()
#         times_ms.append((t1 - t0) * 1000.0)
# 
#         if res.boxes is not None and len(res.boxes) > 0:
#             xyxy = res.boxes.xyxy.cpu().numpy()
#             conf = res.boxes.conf.cpu().numpy()
#             cls = res.boxes.cls.cpu().numpy().astype(int)
# 
#             for j in range(len(cls)):
#                 predictions.append(
#                     {
#                         "image_id": f"img_{i:04d}",
#                         "class_id": int(cls[j]),
#                         "score": float(conf[j]),
#                         "bbox_xyxy": [float(x) for x in xyxy[j].tolist()],
#                     }
#                 )
# 
#     return predictions, times_ms
# 
# 
# def write_outputs(out_dir, backend, images, imgsz, predictions, times_ms):
#     (out_dir / f"predictions_{backend}.json").write_text(json.dumps(predictions, indent=2))
# 
#     lat = summarize_latency_ms(times_ms)
#     latency_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         **lat
#     }
#     ])
#     latency_df.to_csv(out_dir / f"latency_{backend}.csv", index=False)
# 
#     # Placeholder metrics for now
#     metrics_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         "mAP50": None
#     }
#     ])
#     metrics_df.to_csv(out_dir / f"metrics_{backend}.csv", index=False)
# 
#     print("Wrote:", out_dir / f"predictions_{backend}.json")
#     print("Wrote:", out_dir / f"latency_{backend}.csv")
#     print("Wrote:", out_dir / f"metrics_{backend}.csv")
# 
# 
# def main():
#     args = parse_args()
#     backend = args.backend
#     out_dir = Path(args.out)
#     out_dir.mkdir(parents=True, exist_ok=True)
# 
#     image_list = get_image_list(args.images)
# 
#     if args.backend == "pytorch":
#         model = YOLO(args.weights)
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # Changed from 'cpu' to 0 for GPU
#         )
#         write_outputs(out_dir, "pytorch", args.images, args.imgsz, preds, times_ms)
# 
#     elif args.backend == "onnx":
#         # Revert changes: Ultralytics YOLO constructor handles ONNX session internally
#         # and implicitly uses CUDA if onnxruntime-gpu is installed and CUDA is available.
#         # Removing explicit session passing that caused TypeError.
#         model = YOLO(args.onnx_path)  # Ultralytics will run ONNX via onnxruntime
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # GPU
#         )
#         write_outputs(out_dir, "onnx", args.images, args.imgsz, preds, times_ms)
# 
# 
# if __name__ == "__main__":
#     main()

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model.val(data="coco.yaml", split="val", imgsz=640, device=0)

print("mAP50:", results.box.map50)
print("mAP50-95:", results.box.map)
print("Precision:", results.box.mp)
print("Recall:", results.box.mr)

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
results = model.val(data="coco.yaml", split="val", imgsz=640, device=0)

print("mAP50:", results.box.map50)
print("mAP50-95:", results.box.map)
print("Precision:", results.box.mp)
print("Recall:", results.box.mr)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile benchmark.py
# import argparse
# import json
# import time
# from pathlib import Path
# 
# import numpy as np
# import pandas as pd
# 
# from ultralytics import YOLO
# import onnxruntime as ort
# 
# 
# DEFAULT_IMAGES = [
#     "data_samples/bus.jpg",
#     "data_samples/zidane.jpg",
# ]
# 
# 
# def parse_args():
#     p = argparse.ArgumentParser()
#     p.add_argument("--backend", choices=["pytorch", "onnx"], required=True)
#     p.add_argument("--images", type=int, default=10)
#     p.add_argument("--out", type=str, default="results/")
#     p.add_argument("--weights", type=str, default="yolov8n.pt")  # for pytorch
#     p.add_argument("--onnx_path", type=str, default="yolov8n.onnx")
#     p.add_argument("--imgsz", type=int, default=640)
#     p.add_argument("--warmup", type=int, default=10)
#     return p.parse_args()
# 
# 
# def summarize_latency_ms(samples_ms):
#     s = np.asarray(samples_ms, dtype=float)
#     return {
#         "mean_ms": float(s.mean()),
#         "p50_ms": float(np.percentile(s, 50)),
#         "p95_ms": float(np.percentile(s, 95)),
#     }
# 
# 
# def get_image_list(n):
#     return (DEFAULT_IMAGES * ((n + len(DEFAULT_IMAGES) - 1) // len(DEFAULT_IMAGES)))[:n]
# 
# 
# def run_ultralytics_backend(model, image_list, imgsz, warmup, device):
#     # Warmup
#     for _ in range(warmup):
#         _ = model.predict(image_list[0], imgsz=imgsz, verbose=False, device=device)
# 
#     predictions = []
#     times_ms = []
# 
#     for i, img in enumerate(image_list):
#         t0 = time.perf_counter()
#         res = model.predict(img, imgsz=imgsz, verbose=False, device=device)[0]
#         # sync for accurate GPU timing (safe even if CPU)
#         try:
#             import torch
#             if torch.cuda.is_available():
#                 torch.cuda.synchronize()
#         except Exception:
#             pass
#         t1 = time.perf_counter()
#         times_ms.append((t1 - t0) * 1000.0)
# 
#         if res.boxes is not None and len(res.boxes) > 0:
#             xyxy = res.boxes.xyxy.cpu().numpy()
#             conf = res.boxes.conf.cpu().numpy()
#             cls = res.boxes.cls.cpu().numpy().astype(int)
# 
#             for j in range(len(cls)):
#                 predictions.append(
#                     {
#                         "image_id": f"img_{i:04d}",
#                         "class_id": int(cls[j]),
#                         "score": float(conf[j]),
#                         "bbox_xyxy": [float(x) for x in xyxy[j].tolist()],
#                     }
#                 )
# 
#     return predictions, times_ms
# 
# 
# def write_outputs(out_dir, backend, images, imgsz, predictions, times_ms):
#     (out_dir / f"predictions_{backend}.json").write_text(json.dumps(predictions, indent=2))
# 
#     lat = summarize_latency_ms(times_ms)
#     latency_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         **lat
#     }
#     ])
#     latency_df.to_csv(out_dir / f"latency_{backend}.csv", index=False)
# 
#     # Placeholder metrics for now
#     metrics_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         "mAP50": None
#     }
#     ])
#     metrics_df.to_csv(out_dir / f"metrics_{backend}.csv", index=False)
# 
#     print("Wrote:", out_dir / f"predictions_{backend}.json")
#     print("Wrote:", out_dir / f"latency_{backend}.csv")
#     print("Wrote:", out_dir / f"metrics_{backend}.csv")
# 
# 
# 
# def main():
#     args = parse_args()
#     backend = args.backend
#     out_dir = Path(args.out)
#     out_dir.mkdir(parents=True, exist_ok=True)
# 
#     image_list = get_image_list(args.images)
# 
#     if args.backend == "pytorch":
#         model = YOLO(args.weights)
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # Changed from 'cpu' to 0 for GPU
#         )
#         write_outputs(out_dir, "pytorch", args.images, args.imgsz, preds, times_ms)
# 
#     elif args.backend == "onnx":
#         # Revert changes: Ultralytics YOLO constructor handles ONNX session internally
#         # and implicitly uses CUDA if onnxruntime-gpu is installed and CUDA is available.
#         # Removing explicit session passing that caused TypeError.
#         model = YOLO(args.onnx_path)  # Ultralytics will run ONNX via onnxruntime
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # GPU
#         )
#         write_outputs(out_dir, "onnx", args.images, args.imgsz, preds, times_ms)
# 
# 
# if __name__ == "__main__":
#     main()
#

"""**Reasoning**:
The `benchmark.py` script requires sample images in a `data_samples` directory. This step will re-create the directory and download the specified images to ensure the script has the necessary input files to run without errors, as the repository was freshly cloned and is empty.


"""

import os
import requests

# Create data_samples directory if it doesn't exist
data_samples_dir = "data_samples"
os.makedirs(data_samples_dir, exist_ok=True)

# Define image URLs and local paths
image_urls = {
    "bus.jpg": "https://ultralytics.com/images/bus.jpg",
    "zidane.jpg": "https://ultralytics.com/images/zidane.jpg"
}

# Download images
for filename, url in image_urls.items():
    filepath = os.path.join(data_samples_dir, filename)
    if not os.path.exists(filepath):
        print(f"Downloading {filename}...")
        r = requests.get(url, stream=True)
        r.raise_for_status() # Raise an exception for HTTP errors
        with open(filepath, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"Downloaded {filename}")
    else:
        print(f"{filename} already exists, skipping download.")

print(f"Contents of {data_samples_dir}:")
get_ipython().system(f'ls {data_samples_dir}')

"""**Reasoning**:
After re-creating the `benchmark.py` script and `data_samples` directory, the next step is to re-export the PyTorch YOLOv8n model to ONNX format. This will create the `yolov8n.onnx` file, which is required for the ONNX backend benchmarking, as the repository was freshly cloned and is empty.


"""

import pandas as pd
import os

output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Load latency results for PyTorch
latency_pytorch_path = os.path.join(output_dir_drive, 'latency_pytorch.csv')
latency_pytorch_df = pd.read_csv(latency_pytorch_path)

# Load latency results for ONNX
latency_onnx_path = os.path.join(output_dir_drive, 'latency_onnx.csv')
latency_onnx_df = pd.read_csv(latency_onnx_path)

# Concatenate the dataframes
combined_latency_df = pd.concat([latency_pytorch_df, latency_onnx_df], ignore_index=True)

print("Combined Latency Results (ms):\n")
print(combined_latency_df.to_markdown(index=False))

import os

data_samples_dir = "data_samples"

# Check if the directory exists
if not os.path.exists(data_samples_dir):
    print(f"Error: Directory '{data_samples_dir}' does not exist.")
else:
    print(f"Contents of '{data_samples_dir}':")
    !ls -l {data_samples_dir}

import pandas as pd
import os

output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'
output_csv_path = os.path.join(output_dir_drive, 'pure_forward_pass_metrics.csv')

# Load and display the content of the CSV file
if os.path.exists(output_csv_path):
    df_forward_pass = pd.read_csv(output_csv_path)
    print("Content of pure_forward_pass_metrics.csv:")
    print(df_forward_pass.to_markdown(index=False))
    display(df_forward_pass)
else:
    print(f"Error: The file '{output_csv_path}' was not found.")

import pandas as pd
import os

# Define the output directory in Google Drive
output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Create a DataFrame for the pure forward pass benchmark results
combined_forward_pass_df = pd.DataFrame({
    'backend': ['pytorch', 'onnx'],
    'fps': [pt_fps, onnx_fps],
    'ms_per_img': [pt_ms, onnx_ms]
})

# Display the DataFrame
print("Combined Pure Forward Pass Benchmark Results:")
print(combined_forward_pass_df.to_markdown(index=False))
display(combined_forward_pass_df)

# Define the path for the new CSV file
output_csv_path = os.path.join(output_dir_drive, 'pure_forward_pass_metrics.csv')

# Save the DataFrame to a CSV file
combined_forward_pass_df.to_csv(output_csv_path, index=False)
print(f"\nSaved combined pure forward pass metrics to: {output_csv_path}")

# Verify the file is in the directory
print(f"\nContents of {output_dir_drive}:")
!ls -la "{output_dir_drive}"

"""## Export YOLOv8n to ONNX

### Subtask:
Export the `yolov8n.pt` PyTorch model to `yolov8n.onnx` format. This step is necessary to provide the ONNX model required by the ONNX backend benchmark.
"""

from ultralytics import YOLO

# Load the PyTorch YOLOv8n model
model = YOLO('yolov8n.pt')

# Export the model to ONNX format
# The output file will be yolov8n.onnx in the current directory
model.export(format='onnx', imgsz=640)

print("YOLOv8n model exported to yolov8n.onnx")

"""# Task
Benchmark YOLOv8n models using PyTorch and ONNX backends on GPU, combine the `latency_pytorch.csv` and `latency_onnx.csv` files, calculate Frames Per Second (FPS) for each backend, display the combined results, and save them to `combined_benchmark_results.csv` in "/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/".

## Run ONNX Benchmark

### Subtask:
Execute the `benchmark.py` script for the ONNX backend on GPU. This step will use the previously exported `yolov8n.onnx` model and generate `latency_onnx.csv` in the specified Google Drive output directory.

**Reasoning**:
The previous code block failed due to a ValueError indicating that CUDA was not available. This is unexpected as the Colab runtime is set to GPU. I need to explicitly check if CUDA is available in the environment to diagnose the issue further. This will help confirm the CUDA setup before retrying the ONNX benchmark.
"""

import torch
import onnxruntime as ort

print(f"torch.cuda.is_available(): {torch.cuda.is_available()}")
print(f"torch.cuda.device_count(): {torch.cuda.device_count()}")
print(f"ONNX Runtime providers: {ort.get_available_providers()}")

"""**Reasoning**:
The previous cell failed because 'onnxruntime' was not found. I need to install `onnxruntime-gpu` to resolve this dependency issue and enable GPU support for ONNX inference.


"""

pip install onnxruntime-gpu

"""**Reasoning**:
The `onnxruntime-gpu` package has been successfully installed, which should resolve the `ModuleNotFoundError`. Now that the dependency is in place, I will re-run the CUDA availability check to confirm that `onnxruntime` can be imported and correctly identifies the CUDA Execution Provider.


"""

import torch
import onnxruntime as ort

print(f"torch.cuda.is_available(): {torch.cuda.is_available()}")
print(f"torch.cuda.device_count(): {torch.cuda.device_count()}")
print(f"ONNX Runtime providers: {ort.get_available_providers()}")

"""**Reasoning**:
With `onnxruntime-gpu` installed and CUDA confirmed to be available, I will now execute the `benchmark.py` script for the ONNX backend on GPU, directing the output to the specified Google Drive folder as per the subtask instructions.


"""

import os

# Define the output directory in Google Drive
output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Create the output directory if it doesn't exist
os.makedirs(output_dir_drive, exist_ok=True)
print(f"Ensured output directory exists: {output_dir_drive}")

# Run the benchmark for ONNX backend on GPU
# The script is designed to use device=0 (GPU) when onnxruntime-gpu is installed
get_ipython().system(f'python benchmark.py --backend onnx --out "{output_dir_drive}" --imgsz 640 --images 10')

"""**Reasoning**:
The previous command failed because `benchmark.py` was not found in the current directory. I need to ensure the script is executed from the correct path, which is the repository root (`AI-Engineering-Evalution-Export-and-Optimization`). I will navigate to this directory before running the Python script.


"""

# Commented out IPython magic to ensure Python compatibility.
import os

# Define the repository directory
repo_dir = "AI-Engineering-Evalution-Export-and-Optimization"

# Change to the repository directory if not already there
current_path = os.getcwd()
if not current_path.endswith(repo_dir):
#     %cd {repo_dir}
    print(f"Changed directory to: {os.getcwd()}")
else:
    print(f"Already in directory: {os.getcwd()}")

# Define the output directory in Google Drive
output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Create the output directory if it doesn't exist
os.makedirs(output_dir_drive, exist_ok=True)
print(f"Ensured output directory exists: {output_dir_drive}")

# Run the benchmark for ONNX backend on GPU
# The script is designed to use device=0 (GPU) when onnxruntime-gpu is installed
get_ipython().system(f'python benchmark.py --backend onnx --out "{output_dir_drive}" --imgsz 640 --images 10')

"""**Reasoning**:
The previous command failed because the repository directory `AI-Engineering-Evalution-Export-and-Optimization` was not found in `/content`. To correctly execute the ONNX benchmark, I need to re-clone the repository, navigate into it, re-write the latest `benchmark.py` script, download the necessary sample images, and re-export the PyTorch model to ONNX format, ensuring all dependencies and files are in place within the correct working directory.


"""

# Commented out IPython magic to ensure Python compatibility.
# import os
# import requests
# from ultralytics import YOLO
# 
# # Remove the directory if it exists to ensure a clean clone
# repo_dir_path = "/content/AI-Engineering-Evalution-Export-and-Optimization"
# if os.path.exists(repo_dir_path):
#     !rm -rf {repo_dir_path}
#     print(f"Removed existing directory: {repo_dir_path}")
# 
# # Re-clone the repository
# !git clone https://github.com/bgmgncr/AI-Engineering-Evalution-Export-and-Optimization.git
# print("Repository re-cloned.")
# 
# # Change into the repository directory
# %cd AI-Engineering-Evalution-Export-and-Optimization
# print(f"Changed directory to: {os.getcwd()}")
# 
# # Re-write the corrected benchmark.py file
# %%writefile benchmark.py
# import argparse
# import json
# import time
# from pathlib import Path
# 
# import numpy as np
# import pandas as pd
# 
# from ultralytics import YOLO
# import onnxruntime as ort
# 
# 
# DEFAULT_IMAGES = [
#     "data_samples/bus.jpg",
#     "data_samples/zidane.jpg",
# ]
# 
# 
# def parse_args():
#     p = argparse.ArgumentParser()
#     p.add_argument("--backend", choices=["pytorch", "onnx"], required=True)
#     p.add_argument("--images", type=int, default=10)
#     p.add_argument("--out", type=str, default="results/")
#     p.add_argument("--weights", type=str, default="yolov8n.pt")  # for pytorch
#     p.add_argument("--onnx_path", type=str, default="yolov8n.onnx")
#     p.add_argument("--imgsz", type=int, default=640)
#     p.add_argument("--warmup", type=int, default=10)
#     return p.parse_args()
# 
# 
# def summarize_latency_ms(samples_ms):
#     s = np.asarray(samples_ms, dtype=float)
#     return {
#         "mean_ms": float(s.mean()),
#         "p50_ms": float(np.percentile(s, 50)),
#         "p95_ms": float(np.percentile(s, 95)),
#     }
# 
# 
# def get_image_list(n):
#     return (DEFAULT_IMAGES * ((n + len(DEFAULT_IMAGES) - 1) // len(DEFAULT_IMAGES)))[:n]
# 
# 
# def run_ultralytics_backend(model, image_list, imgsz, warmup, device):
#     # Warmup
#     for _ in range(warmup):
#         _ = model.predict(image_list[0], imgsz=imgsz, verbose=False, device=device)
# 
#     predictions = []
#     times_ms = []
# 
#     for i, img in enumerate(image_list):
#         t0 = time.perf_counter()
#         res = model.predict(img, imgsz=imgsz, verbose=False, device=device)[0]
#         # sync for accurate GPU timing (safe even if CPU)
#         try:
#             import torch
#             if torch.cuda.is_available():
#                 torch.cuda.synchronize()
#         except Exception:
#             pass
#         t1 = time.perf_counter()
#         times_ms.append((t1 - t0) * 1000.0)
# 
#         if res.boxes is not None and len(res.boxes) > 0:
#             xyxy = res.boxes.xyxy.cpu().numpy()
#             conf = res.boxes.conf.cpu().numpy()
#             cls = res.boxes.cls.cpu().numpy().astype(int)
# 
#             for j in range(len(cls)):
#                 predictions.append(
#                     {
#                         "image_id": f"img_{i:04d}",
#                         "class_id": int(cls[j]),
#                         "score": float(conf[j]),
#                         "bbox_xyxy": [float(x) for x in xyxy[j].tolist()],
#                     }
#                 )
# 
#     return predictions, times_ms
# 
# 
# def write_outputs(out_dir, backend, images, imgsz, predictions, times_ms):
#     (out_dir / f"predictions_{backend}.json").write_text(json.dumps(predictions, indent=2))
# 
#     lat = summarize_latency_ms(times_ms)
#     latency_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         **lat
#     }
#     ])
#     latency_df.to_csv(out_dir / f"latency_{backend}.csv", index=False)
# 
#     # Placeholder metrics for now
#     metrics_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         "mAP50": None
#     }
#     ])
#     metrics_df.to_csv(out_dir / f"metrics_{backend}.csv", index=False)
# 
#     print("Wrote:", out_dir / f"predictions_{backend}.json")
#     print("Wrote:", out_dir / f"latency_{backend}.csv")
#     print("Wrote:", out_dir / f"metrics_{backend}.csv")
# 
# 
# 
# def main():
#     args = parse_args()
#     backend = args.backend
#     out_dir = Path(args.out)
#     out_dir.mkdir(parents=True, exist_ok=True)
# 
#     image_list = get_image_list(args.images)
# 
#     if args.backend == "pytorch":
#         model = YOLO(args.weights)
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # Changed from 'cpu' to 0 for GPU
#         )
#         write_outputs(out_dir, "pytorch", args.images, args.imgsz, preds, times_ms)
# 
#     elif args.backend == "onnx":
#         # Revert changes: Ultralytics YOLO constructor handles ONNX session internally
#         # and implicitly uses CUDA if onnxruntime-gpu is installed and CUDA is available.
#         # Removing explicit session passing that caused TypeError.
#         model = YOLO(args.onnx_path)  # Ultralytics will run ONNX via onnxruntime
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # GPU
#         )
#         write_outputs(out_dir, "onnx", args.images, args.imgsz, preds, times_ms)
# 
# 
# if __name__ == "__main__":
#     main()
# 
# 
# # Create data_samples directory if it doesn't exist
# data_samples_dir = "data_samples"
# os.makedirs(data_samples_dir, exist_ok=True)
# 
# # Define image URLs and local paths
# image_urls = {
#     "bus.jpg": "https://ultralytics.com/images/bus.jpg",
#     "zidane.jpg": "https://ultralytics.com/images/zidane.jpg"
# }
# 
# # Download images
# for filename, url in image_urls.items():
#     filepath = os.path.join(data_samples_dir, filename)
#     if not os.path.exists(filepath):
#         print(f"Downloading {filename}...")
#         r = requests.get(url, stream=True)
#         r.raise_for_status() # Raise an exception for HTTP errors
#         with open(filepath, 'wb') as f:
#             for chunk in r.iter_content(chunk_size=8192):
#                 f.write(chunk)
#         print(f"Downloaded {filename}")
#     else:
#         print(f"{filename} already exists, skipping download.")
# 
# print(f"Contents of {data_samples_dir}:")
# %cd ..
# !ls {repo_dir_path}/{data_samples_dir}
# %cd {repo_dir_path}
# 
# # Load the PyTorch YOLOv8n model
# model = YOLO('yolov8n.pt')
# 
# # Export the model to ONNX format
# # The output file will be yolov8n.onnx in the current directory
# model.export(format='onnx', imgsz=640)
# 
# print("YOLOv8n model exported to yolov8n.onnx")

"""**Reasoning**:
The previous cell failed with a `ModuleNotFoundError` for `ultralytics`. I need to install the `ultralytics` package to resolve this dependency before proceeding with re-cloning the repository and other setup steps.


"""

pip install ultralytics

"""**Reasoning**:
The `ultralytics` package has been successfully installed. Now I need to re-execute the previous code block that was attempting to re-clone the repository, re-write the `benchmark.py` file, download sample images, and export the YOLOv8n model to ONNX. This step ensures that all necessary files and the correct environment are set up for the ONNX benchmarking, resolving the `ModuleNotFoundError` that previously occurred.


"""

# Commented out IPython magic to ensure Python compatibility.
# import os
# import requests
# from ultralytics import YOLO
# 
# # Remove the directory if it exists to ensure a clean clone
# repo_dir_path = "/content/AI-Engineering-Evalution-Export-and-Optimization"
# if os.path.exists(repo_dir_path):
#     !rm -rf {repo_dir_path}
#     print(f"Removed existing directory: {repo_dir_path}")
# 
# # Re-clone the repository
# !git clone https://github.com/bgmgncr/AI-Engineering-Evalution-Export-and-Optimization.git
# print("Repository re-cloned.")
# 
# # Change into the repository directory
# %cd AI-Engineering-Evalution-Export-and-Optimization
# print(f"Changed directory to: {os.getcwd()}")
# 
# # Re-write the corrected benchmark.py file
# %%writefile benchmark.py
# import argparse
# import json
# import time
# from pathlib import Path
# 
# import numpy as np
# import pandas as pd
# 
# from ultralytics import YOLO
# import onnxruntime as ort
# 
# 
# DEFAULT_IMAGES = [
#     "data_samples/bus.jpg",
#     "data_samples/zidane.jpg",
# ]
# 
# 
# def parse_args():
#     p = argparse.ArgumentParser()
#     p.add_argument("--backend", choices=["pytorch", "onnx"], required=True)
#     p.add_argument("--images", type=int, default=10)
#     p.add_argument("--out", type=str, default="results/")
#     p.add_argument("--weights", type=str, default="yolov8n.pt")  # for pytorch
#     p.add_argument("--onnx_path", type=str, default="yolov8n.onnx")
#     p.add_argument("--imgsz", type=int, default=640)
#     p.add_argument("--warmup", type=int, default=10)
#     return p.parse_args()
# 
# 
# def summarize_latency_ms(samples_ms):
#     s = np.asarray(samples_ms, dtype=float)
#     return {
#         "mean_ms": float(s.mean()),
#         "p50_ms": float(np.percentile(s, 50)),
#         "p95_ms": float(np.percentile(s, 95)),
#     }
# 
# 
# def get_image_list(n):
#     return (DEFAULT_IMAGES * ((n + len(DEFAULT_IMAGES) - 1) // len(DEFAULT_IMAGES)))[:n]
# 
# 
# def run_ultralytics_backend(model, image_list, imgsz, warmup, device):
#     # Warmup
#     for _ in range(warmup):
#         _ = model.predict(image_list[0], imgsz=imgsz, verbose=False, device=device)
# 
#     predictions = []
#     times_ms = []
# 
#     for i, img in enumerate(image_list):
#         t0 = time.perf_counter()
#         res = model.predict(img, imgsz=imgsz, verbose=False, device=device)[0]
#         # sync for accurate GPU timing (safe even if CPU)
#         try:
#             import torch
#             if torch.cuda.is_available():
#                 torch.cuda.synchronize()
#         except Exception:
#             pass
#         t1 = time.perf_counter()
#         times_ms.append((t1 - t0) * 1000.0)
# 
#         if res.boxes is not None and len(res.boxes) > 0:
#             xyxy = res.boxes.xyxy.cpu().numpy()
#             conf = res.boxes.conf.cpu().numpy()
#             cls = res.boxes.cls.cpu().numpy().astype(int)
# 
#             for j in range(len(cls)):
#                 predictions.append(
#                     {
#                         "image_id": f"img_{i:04d}",
#                         "class_id": int(cls[j]),
#                         "score": float(conf[j]),
#                         "bbox_xyxy": [float(x) for x in xyxy[j].tolist()],
#                     }
#                 )
# 
#     return predictions, times_ms
# 
# 
# def write_outputs(out_dir, backend, images, imgsz, predictions, times_ms):
#     (out_dir / f"predictions_{backend}.json").write_text(json.dumps(predictions, indent=2))
# 
#     lat = summarize_latency_ms(times_ms)
#     latency_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         **lat
#     }
#     ])
#     latency_df.to_csv(out_dir / f"latency_{backend}.csv", index=False)
# 
#     # Placeholder metrics for now
#     metrics_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         "mAP50": None
#     }
#     ])
#     metrics_df.to_csv(out_dir / f"metrics_{backend}.csv", index=False)
# 
#     print("Wrote:", out_dir / f"predictions_{backend}.json")
#     print("Wrote:", out_dir / f"latency_{backend}.csv")
#     print("Wrote:", out_dir / f"metrics_{backend}.csv")
# 
# 
# 
# def main():
#     args = parse_args()
#     backend = args.backend
#     out_dir = Path(args.out)
#     out_dir.mkdir(parents=True, exist_ok=True)
# 
#     image_list = get_image_list(args.images)
# 
#     if args.backend == "pytorch":
#         model = YOLO(args.weights)
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # Changed from 'cpu' to 0 for GPU
#         )
#         write_outputs(out_dir, "pytorch", args.images, args.imgsz, preds, times_ms)
# 
#     elif args.backend == "onnx":
#         # Revert changes: Ultralytics YOLO constructor handles ONNX session internally
#         # and implicitly uses CUDA if onnxruntime-gpu is installed and CUDA is available.
#         # Removing explicit session passing that caused TypeError.
#         model = YOLO(args.onnx_path)  # Ultralytics will run ONNX via onnxruntime
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # GPU
#         )
#         write_outputs(out_dir, "onnx", args.images, args.imgsz, preds, times_ms)
# 
# 
# if __name__ == "__main__":
#     main()
# 
# 
# # Create data_samples directory if it doesn't exist
# data_samples_dir = "data_samples"
# os.makedirs(data_samples_dir, exist_ok=True)
# 
# # Define image URLs and local paths
# image_urls = {
#     "bus.jpg": "https://ultralytics.com/images/bus.jpg",
#     "zidane.jpg": "https://ultralytics.com/images/zidane.jpg"
# }
# 
# # Download images
# for filename, url in image_urls.items():
#     filepath = os.path.join(data_samples_dir, filename)
#     if not os.path.exists(filepath):
#         print(f"Downloading {filename}...")
#         r = requests.get(url, stream=True)
#         r.raise_for_status() # Raise an exception for HTTP errors
#         with open(filepath, 'wb') as f:
#             for chunk in r.iter_content(chunk_size=8192):
#                 f.write(chunk)
#         print(f"Downloaded {filename}")
#     else:
#         print(f"{filename} already exists, skipping download.")
# 
# print(f"Contents of {data_samples_dir}:")
# %cd ..
# !ls {repo_dir_path}/{data_samples_dir}
# %cd {repo_dir_path}
# 
# # Load the PyTorch YOLOv8n model
# model = YOLO('yolov8n.pt')
# 
# # Export the model to ONNX format
# # The output file will be yolov8n.onnx in the current directory
# model.export(format='onnx', imgsz=640)
# 
# print("YOLOv8n model exported to yolov8n.onnx")

"""**Reasoning**:
The `UsageError: Line magic function `%%writefile` not found` occurred because `%%writefile` must be the first line in a code cell. To fix this, I need to separate the repository cleanup, cloning, directory change, `benchmark.py` writing, sample data downloading, and ONNX model export into individual code cells or logical blocks, ensuring `%%writefile` is in its own cell at the top.


"""

# Commented out IPython magic to ensure Python compatibility.
import os
import requests
from ultralytics import YOLO

# Remove the directory if it exists to ensure a clean clone
repo_dir_path = "/content/AI-Engineering-Evalution-Export-and-Optimization"
if os.path.exists(repo_dir_path):
    !rm -rf {repo_dir_path}
    print(f"Removed existing directory: {repo_dir_path}")

# Re-clone the repository
!git clone https://github.com/bgmgncr/AI-Engineering-Evalution-Export-and-Optimization.git
print("Repository re-cloned.")

# Change into the repository directory
# %cd AI-Engineering-Evalution-Export-and-Optimization
print(f"Changed directory to: {os.getcwd()}")

"""**Reasoning**:
The previous command failed because the current working directory (`/content`) was not maintained correctly before attempting to clone the repository and then change into it. The `git clone` command itself failed because it couldn't create the directory, leading to the subsequent `cd` command also failing. I will explicitly change the directory to `/content` first to ensure a stable working directory for cloning, then remove any existing repository, re-clone it, and finally change into the newly cloned repository. I will also separate the `%%writefile` magic command into its own cell as it must be the first line.


"""

# Commented out IPython magic to ensure Python compatibility.
import os
import requests
from ultralytics import YOLO

# Ensure we are in /content directory
# %cd /content
print(f"Current directory: {os.getcwd()}")

# Define the repository directory path
repo_dir_name = "AI-Engineering-Evalution-Export-and-Optimization"
repo_dir_path = os.path.join("/content", repo_dir_name)

# Remove the directory if it exists to ensure a clean clone
if os.path.exists(repo_dir_path):
    !rm -rf {repo_dir_path}
    print(f"Removed existing directory: {repo_dir_path}")

# Re-clone the repository
!git clone https://github.com/bgmgncr/AI-Engineering-Evalution-Export-and-Optimization.git
print("Repository re-cloned.")

# Change into the repository directory
# %cd {repo_dir_name}
print(f"Changed directory to: {os.getcwd()}")

"""**Reasoning**:
Now that the repository is correctly cloned and the working directory is set, I need to rewrite the corrected `benchmark.py` script to include all the necessary modifications that were identified in previous steps (e.g., handling GPU devices for PyTorch and ONNX backends).


"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile benchmark.py
# import argparse
# import json
# import time
# from pathlib import Path
# 
# import numpy as np
# import pandas as pd
# 
# from ultralytics import YOLO
# import onnxruntime as ort
# 
# 
# DEFAULT_IMAGES = [
#     "data_samples/bus.jpg",
#     "data_samples/zidane.jpg",
# ]
# 
# 
# def parse_args():
#     p = argparse.ArgumentParser()
#     p.add_argument("--backend", choices=["pytorch", "onnx"], required=True)
#     p.add_argument("--images", type=int, default=10)
#     p.add_argument("--out", type=str, default="results/")
#     p.add_argument("--weights", type=str, default="yolov8n.pt")  # for pytorch
#     p.add_argument("--onnx_path", type=str, default="yolov8n.onnx")
#     p.add_argument("--imgsz", type=int, default=640)
#     p.add_argument("--warmup", type=int, default=10)
#     return p.parse_args()
# 
# 
# def summarize_latency_ms(samples_ms):
#     s = np.asarray(samples_ms, dtype=float)
#     return {
#         "mean_ms": float(s.mean()),
#         "p50_ms": float(np.percentile(s, 50)),
#         "p95_ms": float(np.percentile(s, 95)),
#     }
# 
# 
# def get_image_list(n):
#     return (DEFAULT_IMAGES * ((n + len(DEFAULT_IMAGES) - 1) // len(DEFAULT_IMAGES)))[:n]
# 
# 
# def run_ultralytics_backend(model, image_list, imgsz, warmup, device):
#     # Warmup
#     for _ in range(warmup):
#         _ = model.predict(image_list[0], imgsz=imgsz, verbose=False, device=device)
# 
#     predictions = []
#     times_ms = []
# 
#     for i, img in enumerate(image_list):
#         t0 = time.perf_counter()
#         res = model.predict(img, imgsz=imgsz, verbose=False, device=device)[0]
#         # sync for accurate GPU timing (safe even if CPU)
#         try:
#             import torch
#             if torch.cuda.is_available():
#                 torch.cuda.synchronize()
#         except Exception:
#             pass
#         t1 = time.perf_counter()
#         times_ms.append((t1 - t0) * 1000.0)
# 
#         if res.boxes is not None and len(res.boxes) > 0:
#             xyxy = res.boxes.xyxy.cpu().numpy()
#             conf = res.boxes.conf.cpu().numpy()
#             cls = res.boxes.cls.cpu().numpy().astype(int)
# 
#             for j in range(len(cls)):
#                 predictions.append(
#                     {
#                         "image_id": f"img_{i:04d}",
#                         "class_id": int(cls[j]),
#                         "score": float(conf[j]),
#                         "bbox_xyxy": [float(x) for x in xyxy[j].tolist()],
#                     }
#                 )
# 
#     return predictions, times_ms
# 
# 
# def write_outputs(out_dir, backend, images, imgsz, predictions, times_ms):
#     (out_dir / f"predictions_{backend}.json").write_text(json.dumps(predictions, indent=2))
# 
#     lat = summarize_latency_ms(times_ms)
#     latency_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         **lat
#     }
#     ])
#     latency_df.to_csv(out_dir / f"latency_{backend}.csv", index=False)
# 
#     # Placeholder metrics for now
#     metrics_df = pd.DataFrame([
#         {
#         "backend": backend,
#         "images": images,
#         "imgsz": imgsz,
#         "mAP50": None
#     }
#     ])
#     metrics_df.to_csv(out_dir / f"metrics_{backend}.csv", index=False)
# 
#     print("Wrote:", out_dir / f"predictions_{backend}.json")
#     print("Wrote:", out_dir / f"latency_{backend}.csv")
#     print("Wrote:", out_dir / f"metrics_{backend}.csv")
# 
# 
# 
# def main():
#     args = parse_args()
#     backend = args.backend
#     out_dir = Path(args.out)
#     out_dir.mkdir(parents=True, exist_ok=True)
# 
#     image_list = get_image_list(args.images)
# 
#     if args.backend == "pytorch":
#         model = YOLO(args.weights)
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # Changed from 'cpu' to 0 for GPU
#         )
#         write_outputs(out_dir, "pytorch", args.images, args.imgsz, preds, times_ms)
# 
#     elif args.backend == "onnx":
#         # Revert changes: Ultralytics YOLO constructor handles ONNX session internally
#         # and implicitly uses CUDA if onnxruntime-gpu is installed and CUDA is available.
#         # Removing explicit session passing that caused TypeError.
#         model = YOLO(args.onnx_path)  # Ultralytics will run ONNX via onnxruntime
#         preds, times_ms = run_ultralytics_backend(
#             model=model,
#             image_list=image_list,
#             imgsz=args.imgsz,
#             warmup=args.warmup,
#             device=0,  # GPU
#         )
#         write_outputs(out_dir, "onnx", args.images, args.imgsz, preds, times_ms)
# 
# 
# if __name__ == "__main__":
#     main()

"""**Reasoning**:
Now that the `benchmark.py` script is correctly written, I need to download the sample images (`bus.jpg` and `zidane.jpg`) into the `data_samples` directory. These images are specified in `benchmark.py` as `DEFAULT_IMAGES` and are essential for the script to run without errors.


"""

import os
import requests

# Create data_samples directory if it doesn't exist
data_samples_dir = "data_samples"
os.makedirs(data_samples_dir, exist_ok=True)

# Define image URLs and local paths
image_urls = {
    "bus.jpg": "https://ultralytics.com/images/bus.jpg",
    "zidane.jpg": "https://ultralytics.com/images/zidane.jpg"
}

# Download images
for filename, url in image_urls.items():
    filepath = os.path.join(data_samples_dir, filename)
    if not os.path.exists(filepath):
        print(f"Downloading {filename}...")
        r = requests.get(url, stream=True)
        r.raise_for_status() # Raise an exception for HTTP errors
        with open(filepath, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)
        print(f"Downloaded {filename}")
    else:
        print(f"{filename} already exists, skipping download.")

print(f"Contents of {data_samples_dir}:")
get_ipython().system(f'ls {data_samples_dir}')

"""**Reasoning**:
Now that the `benchmark.py` script is correctly written and sample data is available, I need to export the `yolov8n.pt` PyTorch model to ONNX format. This will generate the `yolov8n.onnx` file required for the ONNX backend benchmark, as defined in the subtask.


"""

from ultralytics import YOLO

# Load the PyTorch YOLOv8n model
model = YOLO('yolov8n.pt')

# Export the model to ONNX format
# The output file will be yolov8n.onnx in the current directory
model.export(format='onnx', imgsz=640)

print("YOLOv8n model exported to yolov8n.onnx")

"""**Reasoning**:
With the `yolov8n.onnx` model successfully exported and the environment correctly configured (including `onnxruntime-gpu` and `ultralytics` installations, and the `benchmark.py` script fixed and data samples present), the next step is to run the benchmark for the ONNX backend on GPU. This will generate the performance results and save them to the specified Google Drive path, as per the subtask instructions.


"""

import os

# Define the output directory in Google Drive
output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Create the output directory if it doesn't exist
os.makedirs(output_dir_drive, exist_ok=True)
print(f"Ensured output directory exists: {output_dir_drive}")

# Run the benchmark for ONNX backend on GPU
# The script is designed to use device=0 (GPU) when onnxruntime-gpu is installed
get_ipython().system(f'python benchmark.py --backend onnx --out "{output_dir_drive}" --imgsz 640 --images 10')

"""**Reasoning**:
The ONNX benchmark has completed successfully, and the `latency_onnx.csv` and `latency_pytorch.csv` files are now available. The next step, as per the main task, is to combine these latency results, calculate the Frames Per Second (FPS) for each backend, display the combined data, and save it to a new CSV file named `combined_benchmark_results.csv` in the specified Google Drive output directory.


"""

import pandas as pd
import os

# Define the output directory in Google Drive
output_dir_drive = '/content/drive/MyDrive/Colab Notebooks/AI-Engineering(Evalution,Export and Optimization)/results/'

# Load latency results for PyTorch and ONNX
latency_pytorch_path = os.path.join(output_dir_drive, 'latency_pytorch.csv')
latency_onnx_path = os.path.join(output_dir_drive, 'latency_onnx.csv')

# Check if files exist before loading
if not os.path.exists(latency_pytorch_path):
    raise FileNotFoundError(f"PyTorch latency file not found: {latency_pytorch_path}")
if not os.path.exists(latency_onnx_path):
    raise FileNotFoundError(f"ONNX latency file not found: {latency_onnx_path}")

latency_pytorch_df = pd.read_csv(latency_pytorch_path)
latency_onnx_df = pd.read_csv(latency_onnx_path)

# Concatenate the dataframes
combined_latency_df = pd.concat([latency_pytorch_df, latency_onnx_df], ignore_index=True)

# Calculate FPS for each backend
# FPS = 1000 / mean_ms
combined_latency_df['fps'] = 1000 / combined_latency_df['mean_ms']

print("Combined Latency Results (ms) and FPS:")
print(combined_latency_df.to_markdown(index=False))

# Define the path for the combined CSV file
combined_csv_path = os.path.join(output_dir_drive, 'combined_benchmark_results.csv')

# Save the combined DataFrame to a CSV file
combined_latency_df.to_csv(combined_csv_path, index=False)
print(f"\nSaved combined benchmark results to: {combined_csv_path}")

# Verify the file is in the directory
print(f"\nContents of {output_dir_drive}:")
get_ipython().system(f'ls -la "{output_dir_drive}"')